### ISSUE TITLE
Add Key Type

### ISSUE THREAD

**Issue by Hyruma** [jchristn/Caching#1]
Hi, is it possible to add an option for change the data type of the key?
I'm using the LRUCache and i don't want String as Key in my application.

Thank you in advance

**Comment by jchristn** [comment]
Hi @Hyruma what kind of object would you like to use as a key?

**Comment by Hyruma** [comment]
Thank for your answer, i would use a custom object, so i think Generic will be fine

**Comment by jchristn** [comment]
Hi @Hyruma it might make the design a little awkward to take a type as part of the constructor to indicate the type of the key (but it's certainly doable).  I'm open to doing it (if I can minimize complexity for the consumer), but was curious if you could give me visibility into and understanding of your use case and why you'd prefer to not use a string for a key?  Thanks!

**Comment by Hyruma** [comment]
Yes of course. The are two reasons:

First, i'm working in a streaming context. My custom object needs to be fast with some functions. To do this i never use the ToString method because is too heavy in terms of computational time.
Second, generally speaking, if i have an int, i have to convert it into a string and getHashCode and Equals of String are a little bit slower.

By the way, I tried to modify your class in local and i convert its definition into 
`LRUCache<T1,T2>`
I did only simple things and i removed some useless code just for me, but it seems work.

Thank you for your fast reply :)

**Comment by jchristn** [comment]
Hi @Hyruma - something like this?  https://gist.github.com/jchristn/21deb1eb35c0988d738381e6d9d564a2  

Let me know if this is what you had in mind (or similar to what you had made) and I'll make the changes on my end and re-publish to NuGet.  Thanks!

**Comment by jchristn** [comment]
Hi @Hyruma just implemented these changes.  Please see commit https://github.com/jchristn/Caching/commit/529f7f76febdb373db90d346c76c1536ccb68b7f

I also updated NuGet to v1.2.0 - it should be available in the next 20 minutes or so: https://www.nuget.org/packages/Caching.dll/1.2.0

Thanks for the suggestion and please let me know of any issues!

**Comment by Hyruma** [comment]
Yes, it is exactly what i did :) Thank you for all
