### ISSUE TITLE
Patch release contains breaking changes

### ISSUE THREAD

**Issue by DomasM** [jchristn/Caching#2]
Hi,
New 1.3.5 release differs from previous 1.3.4 only by patch (e.g. major.minor.patch) but contains breaking changes, like removal of some constructors. Such changes are against SemVer and make life harded for all devs using this library.

**Comment by jchristn** [comment]
Sorry about that, I should have revved it to 1.4. Duly noted and please accept my apology.

**Comment by jchristn** [comment]
I've educated myself on this as well, thanks for pointing it out.  https://semver.org/

**Comment by jchristn** [comment]
Also I'll amend with a new patch that fixes this:
```
What do I do if I accidentally release a backwards incompatible change as a minor version?
As soon as you realize that you’ve broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned releases. If it’s appropriate, document the offending version and inform your users of the problem so that they are aware of the offending version.
```

**Comment by jchristn** [comment]
NuGet: https://www.nuget.org/packages/Caching.dll/1.3.5.1
Commit: https://github.com/jchristn/Caching/commit/a21a8f9af4b2e641244816c06dad0fd0d916a41b

The commit brings back the debug parameter into the constructor as optional.  I'll deprecate in 1.4.

**Comment by DomasM** [comment]
That's great to hear, thanks!
